import { useState } from 'react';
import { Btn, PageHead } from '../components/ui';

const selectProduct = (item, page, go) => { localStorage.setItem('raja_selected_product', JSON.stringify(item)); go(page, { keepOrder: page === 'contact' }); };
export function ProductsPage({ go, content }) {
  const [term, setTerm] = useState(''); const [category, setCategory] = useState(''); const items = content?.products || [];
  const filtered = items.filter(item => `${item.name} ${item.category}`.toLowerCase().includes(term.toLowerCase()) && (!category || item.category === category));
  return <><PageHead crumb="Products" title={<>Our <em>Products</em></>} desc="Browse our wide range of premium quality products."/><section className="catalog"><aside className="product-categories"><h3>Categories</h3><div className="category-filter-list"><button className={!category ? 'selected' : ''} onClick={() => setCategory('')}>All products</button>{(content?.categories || []).map(item => <button className={category === item.name ? 'selected' : ''} key={item.id} onClick={() => setCategory(item.name)}>{item.name}</button>)}</div></aside><main><div className="find"><input placeholder="Search products..." value={term} onChange={event => setTerm(event.target.value)}/><Btn>Search</Btn></div><div className="product-grid">{filtered.map(item => <article key={item.id} className="product-card"><button className="product-open" onClick={() => selectProduct(item, 'productdetail', go)}><img src={item.image} alt={item.name}/><h3>{item.name}</h3><p>{item.price} - {item.category}</p></button><button className="order-product" onClick={() => selectProduct(item, 'contact', go)}>Order / quote</button></article>)}</div>{!filtered.length && <p>No products match your search.</p>}</main></section></>;
}

export function ProductDetailPage({ go, content }) {
  const selected = (() => { try { return JSON.parse(localStorage.getItem('raja_selected_product')); } catch { return null; } })();
  const product = selected && (content?.products || []).find(item => item.id === selected.id) || selected;
  if (!product) return <section className="page-loading">Choose a product from our catalogue to view its details.</section>;
  const features = (product.features || '').split('\n').filter(Boolean); const specifications = (product.specifications || '').split('\n').map(line => line.split('|')).filter(parts => parts.length > 1); const colors = (product.colors || '#f5bd13,#ef2b1c,#ffffff,#111111').split(','); const related = (content?.products || []).filter(item => item.id !== product.id && (item.category === product.category || true)).slice(0, 5);
  const requestProduct = () => selectProduct(product, 'contact', go); const whatsapp = `https://wa.me/${String(content?.site?.whatsappNumber || '').replace(/\D/g, '')}?text=${encodeURIComponent(`Hello, I am interested in ${product.name}.`)}`;
  return <><div className="crumb">Home / {product.category} / {product.name}</div><section className="detail"><div className="product-image"><span>{product.badge || 'Product'}</span><img src={product.image} alt={product.name}/></div><div className="detail-copy"><small>{product.category}</small><h1>{product.name}</h1><p>{product.description}</p>{features.length > 0 && <ul>{features.map(feature => <li key={feature}>{feature}</li>)}</ul>}<div className="swatches">{colors.map(color => <i key={color} style={{ background: color.trim() }} />)}</div><Btn onClick={requestProduct}>Request this product</Btn>{product.catalogUrl ? <a className="catalog-download" href={product.catalogUrl} download={`${product.name}-catalogue`}>Download catalogue</a> : <button className="catalog-download unavailable" disabled>Catalogue coming soon</button>}</div><aside className="details-box"><h3>Product Details</h3>{specifications.map(([label, value]) => <p key={label}><b>{label}</b><span>{value}</span></p>)}<div className="help"><b>Need help?</b><a href={`tel:${content?.site?.phone || ''}`}>{content?.site?.phone || '+91 99413 36125'}</a><a className="whatsapp-button" href={whatsapp} target="_blank" rel="noreferrer">WhatsApp Us</a></div></aside></section><section className="related"><h2>Related Products</h2>{related.map(item => <button key={item.id} onClick={() => selectProduct(item, 'productdetail', go)}><img src={item.image} alt={item.name}/><b>{item.name}</b></button>)}</section></>;
}

