import { useEffect, useState } from 'react';
import { Menu, ChevronRight, X, Home, Package, Image as ImageIcon, FileText, Boxes, Phone, Users, MessageCircle, FolderKanban } from 'lucide-react';
import rajaMark from '../assets/logo/logo.png';
export function Logo() {
  return <a className="logo" href="#home" aria-label="Raja Electricals 'N' Hardwares home">
    <span className="brand-mark-frame"><img src={rajaMark} alt="" className="brand-mark" /></span>
    <span className="brand-copy"><strong>RAJA</strong><small>Electrical 'N' Hardwares</small></span>
  </a>;
}
const links = [['Home', 'home'], ['About Us', 'about'], ['Products', 'products'], ['Gallery', 'gallery'], ['Brands', 'brands'], ['Contact Us', 'contact']];
export function Header({ go, site, currentPage }) { const [open, setOpen] = useState(false); useEffect(() => { const showMenu = () => setOpen(true); window.addEventListener('openmenu', showMenu); return () => window.removeEventListener('openmenu', showMenu); }, []); const navigate = (event, page) => { event.preventDefault(); go(page); setOpen(false); }; const isActive = page => currentPage === page || (page === 'about' && currentPage === 'aboutus') || (page === 'contact' && currentPage === 'contactus') || (page === 'products' && currentPage === 'productdetail'); const phone = String(site?.whatsappNumber || '9003900533').replace(/\D/g, ''); const whatsapp = `https://wa.me/${phone}?text=${encodeURIComponent(site?.whatsappMessage || 'Hello Raja Electricals')}`; return <><header><Logo /><nav>{links.map(([label, page]) => <a key={page} className={isActive(page) ? 'active' : ''} aria-current={isActive(page) ? 'page' : undefined} href={`#${page}`} onClick={event => navigate(event, page)}>{label}</a>)}<a className="quote" href="#contact" onClick={event => navigate(event, 'contact')}>Request a quote <span aria-hidden="true">→</span></a></nav><button className="menu" aria-label="Open menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></header><a className="whatsapp-float" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Contact us on WhatsApp"><MessageCircle size={23}/></a>{open && <aside className="drawer"><div className="drawer-head"><Logo /><button className="drawer-close" onClick={() => setOpen(false)}><X size={12} /> Back to site</button></div>{links.map(([label, page], index) => { const Icon = [Home, Users, Package, FolderKanban, ImageIcon, Boxes, Phone][index]; return <a key={page} className={isActive(page) ? 'active' : ''} aria-current={isActive(page) ? 'page' : undefined} href={`#${page}`} onClick={event => navigate(event, page)}><Icon size={17} />{label}<ChevronRight size={14} /></a>; })}<a className="quote" href="#contact" onClick={event => navigate(event, 'contact')}>Request a quote <span aria-hidden="true">→</span></a><div className="drawer-stats"><b>25+<small>Years of Trust</small></b><b>5000+<small>Products</small></b><b>2000+<small>Happy Clients</small></b></div></aside>}</>; }
export function Footer({ go, site }) { return <footer><div><b>Quick links</b>{[['aboutus', 'About Us'], ['products', 'Products'], ['projects', 'Projects'], ['gallery', 'Gallery']].map(([page, label]) => <button key={page} onClick={() => go(page)}>{label}</button>)}</div><div><b>Contact us</b><span>{site?.phone || '+91 9003900533'}</span><span>{site?.address || 'Chennai, Tamil Nadu'}</span></div><div><b>Administration</b><button className="footer-admin-login" onClick={() => go('dashboard')}>Admin login</button></div><small>(c) 2026 {site?.businessName || "Raja Electricals 'N' Hardware"}</small></footer>; }
export function BottomNav({ go }) { return <div className="bottom-nav"><button onClick={() => go('home')}><Home />Home</button><button onClick={() => go('products')}><Package />Products</button><button onClick={() => go('projects')}><FolderKanban />Projects</button><button onClick={() => go('contactus')}><FileText />Quote</button><button onClick={() => window.dispatchEvent(new Event('openmenu'))}><Menu />Menu</button></div>; }
