import { useEffect, useState } from 'react';
import { Menu, ChevronRight, X, Home, Package, FolderKanban, Image as ImageIcon, FileText, Boxes, Phone, Users, MessageCircle } from 'lucide-react';
// Add your logo file path here, for example: '/images/my-logo.png'.
const logoSrc = '';

export function Logo() { return <a className="logo" href="#home" aria-label="Site logo"><img src={logoSrc || undefined} alt="" /></a>; }
const links = [['Home', 'home'], ['About Us', 'about'], ['Products', 'products'], ['Projects', 'projects'], ['Gallery', 'gallery'], ['Brands', 'brands'], ['Contact Us', 'contact']];
export function Header({ go, site }) { const [open, setOpen] = useState(false); useEffect(() => { const showMenu = () => setOpen(true); window.addEventListener('openmenu', showMenu); return () => window.removeEventListener('openmenu', showMenu); }, []); const navigate = (event, page) => { event.preventDefault(); go(page); setOpen(false); }; const phone = String(site?.whatsappNumber || '919941336125').replace(/\D/g, ''); const whatsapp = `https://wa.me/${phone}?text=${encodeURIComponent(site?.whatsappMessage || 'Hello Raja Electricals')}`; return <><header><Logo /><nav>{links.map(([label, page]) => <a key={page} href={`#${page}`} onClick={event => navigate(event, page)}>{label}</a>)}<a className="quote" href="#dashboard" onClick={event => navigate(event, 'dashboard')}>Admin login</a></nav><button className="menu" aria-label="Open menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></header><a className="whatsapp-float" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Contact us on WhatsApp"><MessageCircle size={23}/></a>{open && <aside className="drawer"><div className="drawer-head"><Logo /><button className="drawer-close" onClick={() => setOpen(false)}><X size={12} /> Back to site</button></div>{links.map(([label, page], index) => { const Icon = [Home, Users, Package, FolderKanban, ImageIcon, Boxes, Phone][index]; return <a key={page} href={`#${page}`} onClick={event => navigate(event, page)}><Icon size={17} />{label}<ChevronRight size={14} /></a>; })}<a className="quote" href="#dashboard" onClick={event => navigate(event, 'dashboard')}>Admin login</a><div className="drawer-stats"><b>25+<small>Years of Trust</small></b><b>5000+<small>Products</small></b><b>2000+<small>Happy Clients</small></b></div></aside>}</>; }
export function Footer({ go, site }) { return <footer><div><b>Quick links</b>{[['aboutus', 'About Us'], ['products', 'Products'], ['projects', 'Projects'], ['gallery', 'Gallery']].map(([page, label]) => <button key={page} onClick={() => go(page)}>{label}</button>)}</div><div><b>Contact us</b><span>{site?.phone || '+91 99413 36125'}</span><span>{site?.email || 'sales@rkinnovations.com'}</span><span>{site?.address || 'Chennai, Tamil Nadu'}</span></div><small>(c) 2026 {site?.businessName || "Raja Electricals 'N' Hardware"}</small></footer>; }
export function BottomNav({ go }) { return <div className="bottom-nav"><button onClick={() => go('home')}><Home />Home</button><button onClick={() => go('products')}><Package />Products</button><button onClick={() => go('projects')}><FolderKanban />Projects</button><button onClick={() => go('contactus')}><FileText />Quote</button><button onClick={() => window.dispatchEvent(new Event('openmenu'))}><Menu />Menu</button></div>; }

